### PR TITLE
Add macOS terminal port

### PR DESCRIPTION
**Pull request by chouzan**
I added macOS terminal port.

### CODE REVIEW

**Comment by jasonm23** [comment]
Thank you

Please remove .DS_Store and force push

**Comment by jasonm23** [comment]
I will add .DS_Store to .gitignore

**Comment by jasonm23** [comment]
a4c75c48f2c5916f4935d89e3a2d4cb356a06043

**Comment by jasonm23** [comment]
Tginking about it, you should add this PR upstream on @poorchop 's repo.

**Comment by chouzan** [comment]
Right, I didn't see the source repo at first

**Pull request closed without merging**
